import { readFile, writeFile } from "node:fs/promises"
import { existsSync } from "node:fs"
import path from "node:path"
import { fileURLToPath } from "node:url"

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..")
const SRC = path.join(root, "src", "session", "writer-prompt.txt")
const OUT = path.join(root, "src", "session", "prompt.ts")

// The writer prompt used to exist twice: writer-prompt.txt (read at runtime by
// the production deploy entry via fs.readFileSync) and prompt.ts (the inlined
// WRITER_PROMPT constant the npm bundle imports). Nothing kept them in step, so
// editing one silently shipped a plugin whose two deployment forms disagreed
// about what the sub-agent is asked to produce. The .txt is the single source;
// this script derives the module from it.
const HEADER = `// AUTO-GENERATED from src/session/writer-prompt.txt by scripts/gen-prompt.mjs
// Do not edit this file — edit the .txt and re-run \`npm run gen:prompt\`.
`

function escapeForTemplateLiteral(text) {
  return text.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${")
}

export async function renderPrompt() {
  const raw = await readFile(SRC, "utf8")
  const normalized = raw.replace(/\r\n/g, "\n").replace(/\n+$/, "")
  return `${HEADER}export const WRITER_PROMPT = \`${escapeForTemplateLiteral(normalized)}\n\`\n`
}

const isMain = process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)
if (isMain) {
  const check = process.argv.includes("--check")
  const next = await renderPrompt()
  const current = existsSync(OUT) ? await readFile(OUT, "utf8") : null
  if (check) {
    if (current !== next) {
      console.error("prompt.ts 与 writer-prompt.txt 不一致。运行: npm run gen:prompt")
      process.exit(1)
    }
    console.log("prompt.ts 与 writer-prompt.txt 一致")
  } else {
    await writeFile(OUT, next, "utf8")
    console.log(`已生成 src/session/prompt.ts (${Buffer.byteLength(next, "utf8")} 字节)`)
  }
}
